###
GET http://localhost:3344/users

###
GET http://localhost:3344/users/user12938712398213

###
POST http://localhost:3344/users
Content-Type: application/json

{
    "user_id": "us1231123129131",
    "email": "email@gmail.com",
    "password": "11111",
    "fullName": "Nounce",
    "role_id": "US",
    "phone": "0381948293",
    "createAt": "2024-01-31 14:21:23",
    "status": 1
}

###
PATCH http://localhost:3344/users/user23599252585
Content-Type: application/json

{
    "password": "22222"
}

###
GET http://localhost:3344/products/P001

###
POST http://localhost:3344/products
Content-Type: application/json

{
    "product_id": "us1231123129131",
    "email": "email@gmail.com",
    "password": "11111",
    "fullName": "Nounce",
    "role_id": "US",
    "phone": "0381948293",
    "createAt": "2024-01-31 14:21:23",
    "status": 1
}

###
GET http://localhost:3344/carts/us5833430108618

###
GET http://localhost:3344/cartItems/cart738249201

###
GET http://localhost:3344/products/category/Table

###
GET http://localhost:3344/topProducts

###
GET http://localhost:3344/productsOfTheWeek